FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

ENV INITSYSTEM=on
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update && apt-get install -yq --no-install-recommends build-essential curl i2c-tools \
    python3 python3-pip python3-dev python3-setuptools python3-pil

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY app.py /app/app.py
CMD ["python3", "/app/app.py"]
