FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3-run

ENV INITSYSTEM=on
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update && apt-get install -yq --no-install-recommends build-essential curl i2c-tools \
  python3-pillow
RUN pip3 install urllib3 wheel setuptools

COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY app.py /app/app.py
CMD ["python3", "/app/app.py"]
